name: openwrt

on: 
  release:
    types: [published]

  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo apt install subversion g++ zlib1g-dev build-essential git python python3 python3-distutils libncurses5-dev gawk gettext \
                 unzip file libssl-dev wget libelf-dev ecj fastjar java-propose-classpath libncursesw5-dev
        wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        git clone https://github.com/friendlyarm/repo
        sudo cp repo/repo /usr/bin/

    - name: Download Source
      run: |
        mkdir friendlywrt-h5
        cd friendlywrt-h5
        repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master -m h5.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
        repo sync -c --no-clone-bundle -j8
        
    #- name: Clone source code
    #  run: |
    #    cd friendlywrt-h5 && rm -rf friendlywrt
    #    git clone https://github.com/openwrt/openwrt.git && mv openwrt friendlywrt
    #    #git clone https://github.com/coolsnowwolf/lede.git
    #    cd friendlywrt
    #    git checkout v19.07.2
    #    #cd package
    #    #ln -s ../../lede/package/lean/ lean
        
    - name: Update & Install feeds
      run: |
        #echo src-git lienol https://github.com/Lienol/openwrt-package >> feeds.conf.default
        #cp openwrt_feeds friendlywrt-h5/friendlywrt/feeds.conf.default
        cd friendlywrt-h5/friendlywrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Configuration Customization and build
      env:
        CONFIG_FILE: '2020-03-24.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE friendlywrt-h5/friendlywrt/.config
        #chmod +x ./customize.sh && ./customize.sh
        cd friendlywrt-h5/friendlywrt && make defconfig
        
    - name: Download package
      run: |
        cd friendlywrt-h5/friendlywrt
        make download -j$(nproc)
        
    - name: Build firmware
      run: |
        #echo -e "$(nproc) thread build."
        cd friendlywrt-h5/friendlywrt
        make -j1 V=s

    - name: Build SD img
      run: |
        cd friendlywrt-h5
        sed -i '130,150 {/build_friendlywrt/d}' scripts/build.sh
        ./build.sh nanopi_r1s.mk

    - name: Zip Files
      run: |
        find friendlywrt-h5/out/ -name "FriendlyWrt_*img*" | xargs -i zip -r {}.zip {}
          
    - name: Assemble Artifact
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        find friendlywrt-h5/out/ -name "FriendlyWrt_*img.zip*" | xargs -i mv -f {} ./artifact/
          
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: FriendlyWrt_NanoPi-R1S H5
        path: ./artifact/

    #- name : Upload artifact
    #  uses: actions/upload-artifact@master
    #  with:
    #    name: OpenWrt_fr
    #    path: friendlywrt-h5/friendlywrt/bin
